name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Test Application
        run: |
          pytest 

      - name: Deploy to AWS EC2
        if: github.ref == 'refs/heads/main'
        run: |
          ssh -i "chaves-rec.pem" ec2-user@<IP-da-instância> "cd "C:\Users\melissamartins-ieg\OneDrive - Instituto Germinare\2 ANO - 2024\DevOps\rec-devops\rec-lab-atividade_python" && git pull && sudo systemctl restart api.service"

      - name: Deploy to Render (DEV)
        if: github.ref != 'refs/heads/main'
        run: |
          curl -X POST -H "Authorization: Bearer <API_KEY_RENDER>" \
          -d '{"serviceId": "<SERVICE_ID>", "branch": "dev"}' \
          https://api.render.com/deploy
